### ISSUE TITLE
server.js requires bodyParser which is not include in express

### ISSUE THREAD

**Issue by joshvito** [mariano-fiorentino/amid#4]
after clean install, the server.js doesn't run, as the bodyParser is not included in express

**Comment by mariano-fiorentino** [comment]
It's because is changed express that now non more include the middleware. That's the bodyparser error.
I'm making a new version of the npm pkg that fix the problem, but i hadn't yet the time to complete the task.
In the while you can fix the problem installing manually the body-parser pkg (npm install body-parser), and then changing server.js from:


var express = require('express');
var app = module.exports.app = express();
app.use(express.bodyParser());

to:

var express = require('express');
var bodyParser = require('body-parser');
var app = module.exports.app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

Tell me if works with this.

M

**Comment by joshvito** [comment]
If I run it after I make the substitutions above, i can run with cmd> node server
however, the following errors occur on server startup:
```
/var/www/test/node_modules/amid$ node server
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
express deprecated app.del: Use app.delete instead lib/rest.js:476:5
express deprecated app.del: Use app.delete instead lib/rest.js:546:5
express deprecated app.del: Use app.delete instead lib/rest.js:476:5
express deprecated app.del: Use app.delete instead lib/rest.js:546:5
```

Then if I run a simple curl to insert into db, e.g. 
```
 curl -d '{ "A2" : 201 }' -H "Content-Type: application/json" http://localhost:3000/test/example1
```

The following returns:
```
{ A2: 201 }
========================================================================================
=  Please ensure that you set the default write concern for the database by setting    =
=   one of the options                                                                 =
=                                                                                      =
=     w: (value of > -1 or the string 'majority'), where < 1 means                     =
=        no write acknowledgement                                                       =
=     journal: true/false, wait for flush to journal before acknowledgement             =
=     fsync: true/false, wait for flush to file system before acknowledgement           =
=                                                                                      =
=  For backward compatibility safe is still supported and                              =
=   allows values of [true | false | {j:true} | {w:n, wtimeout:n} | {fsync:true}]      =
=   the default value is false which means the driver receives does not                =
=   return the information of the success/error of the insert/update/remove            =
=                                                                                      =
=   ex: new Db(new Server('localhost', 27017), {safe:false})                           =
=                                                                                      =
=   http://www.mongodb.org/display/DOCS/getLastError+Command                           =
=                                                                                      =
=  The default of no acknowledgement will change in the very near future                =
=                                                                                      =
=  This message will disappear when the default safe is set on the driver Db           =
========================================================================================

/var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
              ^
TypeError: Cannot read property '0' of null
    at /var/www/test/node_modules/amid/lib/rest.js:404:88
    at /var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/collection/core.js:107:73
    at /var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/db.js:1195:7
    at /var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/db.js:1903:9
    at Server.Base._callHandler (/var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at MongoReply.parseBody (/var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/var/www/test/node_modules/amid/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)

```
 Thanks for the help.

**Comment by mariano-fiorentino** [comment]
Yes the problem is the new version of mongo-native driver that have a different behaviour.
I released on npm a brand new package that should  solve this kind of problems. The new working version of amid is 1.2.0.
I made some test and seems that now the package on npm is working again. 

Can you try after an update?

**Comment by joshvito** [comment]
a fresh install runs as expected, thank you
